# Site Settings
title: Resume
url: 'http://iamgubi.xyz'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5 #orange
#style: styles-6 #dark grey

#Profile information
name: Erick Gubi
tagline: Technology Enthusiast
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
#email: hello@webjeda.com
website: letsdocloud.com #do not add http://
linkedin: erickgubi
github: dmnt3d
twitter: '@callmegubi'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-40489712-2

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
